### ISSUE TITLE
Tutorial for beginners

### ISSUE THREAD

**Issue by mtczerwinski** [chaps-io/access-granted#11]
Are you considering to create a tutorial for beginners ? I mean sth which will show how to start or example based on simple rails application. I asked because doc, wiki is poor.

**Comment by janko-m** [comment]
Yeah, I think it would be great to include in the README how a class with `AccessGranted::Policy` included is used, i.e. what are the main methods you can use.

**Comment by pokonski** [comment]
@janko-m it was long overdue and I'm working on it today :) Brand new README is in the works, because the current one is lacking a lot.

**Comment by mtczerwinski** [comment]
:+1:

**Comment by CyberStrike** [comment]
:+1:

**Comment by christianonrails** [comment]
yeah that would be nice. just wanted to replace cancan with access-granted but i got this error already uninitialized constant AccessGranted::Policy. i just wanted to look into the code but if the new readme is in the make then i just wait a bit. thanks for that

**Comment by pokonski** [comment]
@christianonrails yeah that was an unrelated issue, I released a 0.1.1 version which addresses that :)

**Comment by janko-m** [comment]
No problem, thanks for a framework-agnostic authorization and activesupport-free gem, that is really important for me :)

**Comment by pokonski** [comment]
@mtczerwinski @janko-m @christianonrails @CyberStrike I completely redid the Usage section in README!

https://github.com/chaps-io/access-granted#usage

Do check it out and I'd love some feedback if it's easy to follow :)

**Comment by christianonrails** [comment]
i implemented it already. all good. thx a lot
Piotr Okoński <notifications@github.com> schrieb am Fr., 31. Juli 2015 um
16:25:

**Comment by pokonski** [comment]
@christianonrails sweet :cake:
