### ISSUE TITLE
Version 0.2 not published to rubygems

### ISSUE THREAD

**Issue by onordgren** [chaps-io/access-granted#12]
Hi,

Had some issues yesterday setting up this gem in my rails app. Seems like the latest version that is published on rubygems (0.1.1) doesn't include the rails lib. However I managed to solve this by fetching the directly from the git repo so maybe the docs needs to be updated or 0.2 should be published to rubygems.

Thanks!

**Comment by pokonski** [comment]
@onordgren good catch. Publishing 0.2 to Rubygems ASAP :)

**Comment by pokonski** [comment]
And here we go https://rubygems.org/gems/access-granted/versions/0.2

**Comment by onordgren** [comment]
Great!
