### ISSUE TITLE
Bug related to :manage and using multiple operations in permission definition

### ISSUE THREAD

**Issue by vittorius** [chaps-io/access-granted#21]
Hey there. I've spotted a couple of cases where behavior doesn't seem logical:

```ruby
role :admin, proc { |user| user.admin? } do
  can :manage, Merchant # can? :edit @merchant is AccessDenied, :read is OK
end
```

```ruby
role :admin, proc { |user| user.admin? } do
  can [:manage], Merchant # can? :edit @merchant is AccessDenied, :read is AccessDenied
end
```

```ruby
role :admin, proc { |user| user.admin? } do
  can [:manage, :edit], Merchant # can? :edit @merchant is AccessDenied, :read is AccessDenied
end
```

:question: :question: :question:

**Comment by pokonski** [comment]
`can :manage` is only a shortcut right now, it doesn't work with other attributes or inside an array, but this is worth improving so your examples can work, too :)

**Comment by vittorius** [comment]
```ruby
role :admin, proc { |user| user.admin? } do
  can :manage, Merchant # can? :read @merchant is OK
  can :edit, Merchant # can? :edit @merchant is OK
end
```

**Comment by vittorius** [comment]
OK, will take into account. I'm your beta tester for today :smile:

**Comment by pokonski** [comment]
Yeah, see this: https://github.com/chaps-io/access-granted/blob/master/lib/access-granted/role.rb#L71-L75

So when you provide other permissions in separate `can` calls it will work :)

>OK, will take into account. I'm your beta tester for today :smile:

I appreciate that! :D
