### ISSUE TITLE
Permissions with blocks work too persmissive (block is ignored)

### ISSUE THREAD

**Issue by vittorius** [chaps-io/access-granted#24]
Hello.

I have such policy:

```ruby
can [:read, :update, :destroy], User do |user, merchant_admin|
  user.merchant.present? && created_user_is_of_creator_merchant?(merchant_admin, user)
end
```

and check

```ruby
<% if can? :read, User %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>
```

When I add `byebug` to policy block the execution even doesn't get stopped. So, looks like it looks at `User` at decides that it's enough.

Only when I comment out the policy definition, the check works.

**Comment by vittorius** [comment]
Update: looks like block works only when checking the `User` *instances*. But why would such definition permit any operation on class?

**Comment by noorhammad** [comment]
@vittorius  can you document the solution you used to get the block to execute?

**Comment by vittorius** [comment]
It's a dumb hack )

```ruby
<% if current_user.has_privileges?(:admin) %>
```

(`has_privileges?` is just my method for model User which checks the it's in appropriate role)

**Comment by pokonski** [comment]
@vittorius 
> Update: looks like block works only when checking the User instances. But why would such definition permit any operation on class?

because you are not meant to use `:destroy` or `:update` on classes. Because it doesn't make sense, you can't remove a class.

So the only permission usually you need to check on a class is `:create`.
