### ISSUE TITLE
Error when there is no user logged in

### ISSUE THREAD

**Issue by victor0402** [chaps-io/access-granted#35]
I'm using an access policy in my rails 4 app that checks the user role, very similar to the example [here](https://github.com/chaps-io/access-granted#defining-an-access-policy).  

```
role :moderator, proc { |u| u.moderator? } do
  can [:update, :destroy], Post
  can :update, User
end

role :guest do
  can :read, :all
end
```

I got an error when there are no user logged in, because the call `u.moderator?` expects an user and `u` is `nil`.  

To fix this error I needed to override the `initialize` method:
```
def initialize(user)
  user ||= User.new
  super user
end
```

My question is: do I need to check when there is an `@user` in my policy or do I did something wrong applying the gem?  

If I need to check the `@user` i think that would be great update the readme with this info.

**Comment by pokonski** [comment]
See this for a possible solution: https://github.com/chaps-io/access-granted/issues/32
