### ISSUE TITLE
Higher level roles do not seem to inherit from lower level roles

### ISSUE THREAD

**Issue by parc64** [chaps-io/access-granted#41]
Looking at this line from documentation at https://blog.chaps.io/2015/11/13/role-based-authorization-in-rails.html
_Roles inherit from less important roles below them, but only from roles which apply to the given user. So we only need to add additional permissions on top of them. In this case, we will let members create posts and topics:_

I have not been able to get this backward inheritance to work. I have something similar to this in my config.

```
class AccessPolicy
  include AccessGranted::Policy

  def configure
    role :admin, { role: 'admin' } do
       # can :view, Admin::DashboardController
     end

    role :staff, { role: 'staff' } do
      can :view, Admin::DashboardController
    end

    role :view_only, { role: 'view_only' } do

    end
  end
end
```

However calling can? :view, Admin::DashboardController only returns true for the :staff role, and returns false for the higher level :admin role. Unless I uncomment the line in the :admin block.

**Comment by pokonski** [comment]
Hey, @parc64.

AG will only inherit from roles which also apply to the user. So if your user has a `role` set to `admin`, it won't match with role `staff` because it expects `staff` to be inside the `role` attribute. You should update the less important roles to also apply, like this:


```ruby
role :staf, proc { |user| user.role == "staff" || user.role == "admin" } do
```

**Comment by parc64** [comment]
Hello @pokonski ,

Ok that makes sense. It would be nice to update the docs to show this example. The way the docs are now, it's difficult to understand if the gem is doing this behind the scenes or if the user needs to knit these together as your example shows. The docs also talk about the order of the roles in the access_policy.rb file, does the gem actually use the order for anything, or is that just a suggested good practice?

Thanks!

**Comment by pokonski** [comment]
You are absolutely right, it isn't backed by an example, but only a short sentence. I will expand that :) 

And yes order is important because the first role which has a permission you are checking will stop further checks. So if a top role has 'cannot' defined for a permission, then Access Granted will not check the remaining roles.

**Comment by pokonski** [comment]
The order is explained in the Readme here https://github.com/chaps-io/access-granted/blob/master/README.md#roles-in-order-of-importance

**Comment by parc64** [comment]
awesome, thank you

**Comment by rozhok** [comment]
Correct me if I'm wrong, but cant I set-up per-object permissions rather than roles and grant users access using something like bitmask?

**Comment by pokonski** [comment]
@rozhok you don't have to use roles. You can have one role for everything and do whatever check you like inside the `can` block.

**Comment by rozhok** [comment]
Oh really, missed last example, got it.

Okay, but it's not the best way to do that, isn't it?

**Comment by pokonski** [comment]
AG is made specifically to utilize roles, if you don't have roles then yes - it might not be the best way.

**Comment by rozhok** [comment]
I want roles, but I don't want inheritance. Is there way to avoid it?

**Comment by pokonski** [comment]
Yes, roles only inherit each other if two or more roles apply to the same user.

For example this policy:

```

role :admin_role, {role: :admin} do
  (... some permissions here..)
end

role :regular_role, {role: :regular} do
  (...)
end
```

for an admin user like this 

```
current_user.role #=> :admin
```

will not inherit permissions from `regular_role` because that role is not matching the user at all (it would only match if the conditions were satisfied.

**Comment by pokonski** [comment]
Awesome, let me know if AG turned out to be useful :smile:

**Comment by rozhok** [comment]
Everything works as excepted! Awesome. Using it in prod now.

**Comment by pokonski** [comment]
@rozhok fantastic! I do love hearing success stories :D
