### ISSUE TITLE
Object and Subobject

### ISSUE THREAD

**Issue by sadjehwty** [chaps-io/access-granted#44]
How can I define rule for a subobject extends object rule.
es.
```
can :delete, Object do |obj, user|
  post.author_id == user.id
end
can :delete, Subobject do |sub, user|
  can? :delete, sub.parent && sub.id>3
end
```

**Comment by pokonski** [comment]
Hi! If I understood you correctly, then: there is no inheritance between `can` blocks and Access Granted has no special handling for inheritance of Ruby classes.

You can DRY it up by extracting common logic into methods and use that in blocks
