### ISSUE TITLE
Undefined method with ViewComponents

### ISSUE THREAD

**Issue by choilive** [chaps-io/access-granted#54]
I am getting an `undefined method can?` when attempting to use access-granted inside a view component.

https://github.com/github/view_component

Any ideas/suggestions in order to get this to work?

**Comment by choilive** [comment]
Figured it out.

Just needed to add `include AccessGranted::Rails::ControllerMethods` into my component class and delegate `current_user` through the view component `helpers` escape hatch.

**Comment by pokonski** [comment]
That's a good point and probably cleaner :)

**Comment by choilive** [comment]
> I think maybe you could also have delegated the `can?` method to the `helpers`, without `include AccessGranted::Rails::ControllerMethods`?

Ah, that also works.  Will try that for a future project :)
